//
//  ProgressBarDraw.swift
//  ProgressBarFun
//
//  Created by Kritawit Bunket on 1/29/2560 BE.
//  Copyright © 2560 HeaderDev. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//
//  This code was generated by Trial version of PaintCode, therefore cannot be used for commercial purposes.
//



import UIKit

public class ProgressBarDraw : NSObject {

    //// Drawing Methods

    public dynamic class func drawProgressBar(frame: CGRect = CGRect(x: 0, y: 0, width: 300, height: 16), progress: CGFloat = 123) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()!
        // This non-generic function dramatically improves compilation times of complex expressions.
        func fastFloor(_ x: CGFloat) -> CGFloat { return floor(x) }

        //// Color Declarations
        let color = UIColor(red: 0.781, green: 0.132, blue: 0.132, alpha: 1.000)

        //// Progress Border Drawing
        let progressBorderPath = UIBezierPath(roundedRect: CGRect(x: frame.minX + 0.5, y: frame.minY + 0.5, width: fastFloor((frame.width - 0.5) * 0.99833 + 0.5), height: 15), cornerRadius: 7)
        color.setStroke()
        progressBorderPath.lineWidth = 1
        progressBorderPath.stroke()


        //// Progress Active Drawing
        context.saveGState()
        context.translateBy(x: frame.minX + 1, y: frame.minY + 2)

        let progressActivePath = UIBezierPath(roundedRect: CGRect(x: 0, y: -1, width: (progress + 27), height: 14), cornerRadius: 7)
        color.setFill()
        progressActivePath.fill()

        context.restoreGState()
    }

}
